package tavarua

import "fm-go-bin/internal/v4l2"

// https://github.com/kaiostech/gecko-b2g/blob/5e5306693a90c9fc6c9b4a6e12cebb64d9e9a20c/hal/gonk/tavarua.h#L115
const (
	CID_SEARCH_MODE    = (v4l2.CID_PRIVATE_BASE + 1)  // CID_SRCHMODE
	CID_SCAN_DWELL     = (v4l2.CID_PRIVATE_BASE + 2)  // CID_SCANDWELL
	CID_SEARCH_ON      = (v4l2.CID_PRIVATE_BASE + 3)  // CID_SRCHON
	CID_STATE          = (v4l2.CID_PRIVATE_BASE + 4)  // CID_STATE
	CID_TRANSMIT_MODE  = (v4l2.CID_PRIVATE_BASE + 5)  // CID_TRANSMIT_MODE
	CID_RDS_GROUP_MASK = (v4l2.CID_PRIVATE_BASE + 6)  // CID_RDSGROUP_MASK
	CID_REGION         = (v4l2.CID_PRIVATE_BASE + 7)  // CID_REGION
	CID_SIGNAL_TH      = (v4l2.CID_PRIVATE_BASE + 8)  // CID_SIGNAL_TH
	CID_SEARCH_PTY     = (v4l2.CID_PRIVATE_BASE + 9)  // CID_SRCH_PTY
	CID_SEARCH_PI      = (v4l2.CID_PRIVATE_BASE + 10) // CID_SRCH_PI
	CID_SEARCH_CNT     = (v4l2.CID_PRIVATE_BASE + 11) // CID_SRCH_CNT
	CID_EMPHASIS       = (v4l2.CID_PRIVATE_BASE + 12) // CID_EMPHASIS
	CID_RDS_STD        = (v4l2.CID_PRIVATE_BASE + 13) // CID_RDS_STD
	CID_SPACING        = (v4l2.CID_PRIVATE_BASE + 14) // CID_SPACING
	CID_RDS_ON         = (v4l2.CID_PRIVATE_BASE + 15) // CID_RDSON
	CID_RDS_GROUP_PROC = (v4l2.CID_PRIVATE_BASE + 16) // CID_RDSGROUP_PROC
	CID_LP_MODE        = (v4l2.CID_PRIVATE_BASE + 17) // CID_LP_MODE
	CID_ANTENNA        = (v4l2.CID_PRIVATE_BASE + 18) // CID_ANTENNA
	CID_RDSD_BUF       = (v4l2.CID_PRIVATE_BASE + 19) // CID_RDSD_BUF
	CID_PS_ALL         = (v4l2.CID_PRIVATE_BASE + 20) // CID_PSALL
	CID_AF_JUMP        = (v4l2.CID_PRIVATE_BASE + 27) // CID_AF_JUMP
	CID_RSSI_DELTA     = (v4l2.CID_PRIVATE_BASE + 28) // CID_RSSI_DELTA
	CID_HLSI           = (v4l2.CID_PRIVATE_BASE + 29) // CID_HLSI
	CID_SET_AUDIO_PATH = (v4l2.CID_PRIVATE_BASE + 41) // CID_SET_AUDIO_PATH

	// CID_RDSGRP_RT        = (v4l2.CID_PRIVATE_BASE + 62)
	// CID_RDSGRP_PS_SIMPLE = (v4l2.CID_PRIVATE_BASE + 63)
	// CID_RDSGRP_AF_LIST    = (v4l2.CID_PRIVATE_BASE + 64) // CID_RDSGRP_AFLIST
	// CID_RDSGRP_ERT       = (v4l2.CID_PRIVATE_BASE + 65)
	// CID_RDSGRP_RT_PLUS   = (v4l2.CID_PRIVATE_BASE + 66)
	// CID_RDSGRP_3A        = (v4l2.CID_PRIVATE_BASE + 67)
)

// События
const (
	EVT_RADIO_READY = iota
	EVT_TUNE_SUCCESS
	EVT_SEEK_COMPLETE
	EVT_SCAN_NEXT
	EVT_NEW_RAW_RDS
	EVT_NEW_RT_RDS
	EVT_NEW_PS_RDS
	EVT_ERROR
	EVT_BELOW_TH
	EVT_ABOVE_TH
	EVT_STEREO
	EVT_MONO
	EVT_RDS_AVAIL
	EVT_RDS_NOT_AVAIL
	EVT_NEW_SEARCH_LIST
	EVT_NEW_AF_LIST
	_
	_
	EVT_RADIO_DISABLED
	EVT_RDS_GRP_MASK_REQ
	EVT_NEW_RT_PLUS
	ERT_EVENT
	AF_JMP_EVENT
)

// Типы буферов
const (
	BUF_SRCH_LIST = 0
	BUF_EVENTS    = 1
	BUF_RT_RDS    = 2
	BUF_PS_RDS    = 3
	BUF_RAW_RDS   = 4
	BUF_AF_LIST   = 5
	BUF_MAX       = 6
	RT_PLUS_IND   = 11
	ERT_IND       = 12
)

// Состояние радио
const (
	FM_POWER_OFF        = 0
	FM_POWER_TRANSITION = 1
	FM_POWER_ON         = 2
)

const (
	FM_RX_EMP75 = 0x0
	FM_RX_EMP50 = 0x1
)

// Шаг
const (
	FM_RX_SPACE_200KHZ = 0x0
	FM_RX_SPACE_100KHZ = 0x1
	FM_RX_SPACE_50KHZ  = 0x2
)

// Система RDS
const (
	FM_RX_RDBS_SYSTEM   = 0x0
	FM_RX_RDS_SYSTEM    = 0x1
	FM_RX_RDS_NO_SYSTEM = 0x2
)

type PowerMode uint32

const (
	FM_RX_POWER_MODE_NORMAL PowerMode = iota // = 0
	FM_RX_POWER_MODE_LOW                     // = 1
)

const (
	FM_SERVICE_NOT_AVAILABLE = 0x0
	FM_SERVICE_AVAILABLE     = 0x1
)

const (
	FM_RX_NO_MUTE    = 0x00
	FM_RX_MUTE_RIGHT = 0x01
	FM_RX_MUTE_LEFT  = 0x02
	FM_RX_MUTE_BOTH  = 0x03
)
